Repository Philipp-Plotnikov/povaryoshka-bot, pull requests merged in 2025-02, with the labels that each got.

#31 feat: make the ouput information copyable
  app/src/main/java/core/Main.java
  app/src/main/java/core/factory/FacadeFactory.java
  app/src/main/java/dbdrivers/factory/PostgresDbDriverFactory.java
  app/src/main/java/models/commons/SendOptions.java
  app/src/main/java/models/system/EnvVars.java
  app/src/main/java/telegram/commands/AbstractCommand.java
  app/src/main/java/telegram/commands/GetDishCommand.java
Labels: enhancement

#32 fix: changed the ingredient breakdown
  app/src/main/java/language/ru/BotMessages.java
  app/src/main/java/telegram/commands/CreateDishCommand.java
Labels: bug

#34 refactor: unify command context detection
  app/src/main/java/telegram/commands/AbstractCommand.java
  app/src/main/java/telegram/commands/CreateDishCommand.java
  app/src/main/java/telegram/commands/DeleteDishCommand.java
  app/src/main/java/telegram/commands/FeedbackCommand.java
  app/src/main/java/telegram/commands/GetDishCommand.java
  app/src/main/java/telegram/commands/UpdateDishCommand.java
Labels: refactor

#37 feat: add command start
  app/src/main/java/language/ru/BotMessages.java
  app/src/main/java/language/ru/command/settings/Start.java
  app/src/main/java/models/commands/CommandConfig.java
  app/src/main/java/telegram/commands/StartCommand.java
  app/src/main/java/telegram/commands/factory/SimpleCommandFactory.java
Labels: enhancement
